<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.tileverse.parquetry</groupId>
    <artifactId>parquetry-parent</artifactId>
    <version>${revision}</version>
  </parent>

  <artifactId>parquetry-bom</artifactId>
  <packaging>pom</packaging>
  <name>Parquetry :: BOM</name>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.tileverse.parquetry</groupId>
        <artifactId>parquetry-format</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.tileverse.parquetry</groupId>
        <artifactId>parquetry-core</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.tileverse.parquetry</groupId>
        <artifactId>parquetry-encryption</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.tileverse.parquetry</groupId>
        <artifactId>parquetry-variant</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
