/*
 * Copyright (c) 2026 Tileverse.io
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.tileverse.parquetry.format.codec;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import io.tileverse.storage.RangeReader;
import io.tileverse.storage.Storage;
import io.tileverse.storage.StorageFactory;

import io.tileverse.parquetry.format.ColumnChunk;
import io.tileverse.parquetry.format.ColumnIndex;
import io.tileverse.parquetry.format.FileMetaData;
import io.tileverse.parquetry.format.OffsetIndex;
import io.tileverse.parquetry.format.PageHeader;
import io.tileverse.parquetry.format.enums.PageType;

/**
 * Conformance tests for PageHeader, ColumnIndex, and OffsetIndex reading.
 *
 * <p>Validates that parquetry can correctly decode all three page-level structures from real Parquet files generated by
 * the parquet-avro reference writer.
 */
class PageHeaderConformanceTest {

    /**
     * Verifies that ColumnIndex and OffsetIndex can be read for all column chunks in the first row group of a typical
     * Parquet file.
     *
     * <p>The flat-int-snappy fixture has 5 columns and 1000 rows, which ensures the parquet-avro writer emits column
     * and offset indexes.
     */
    @Test
    void columnIndexAndOffsetIndexReadable(@TempDir Path tmp) throws Exception {
        Path file = TestFiles.flatIntSnappy(tmp);
        try (Storage storage = StorageFactory.open(file.getParent().toUri());
                RangeReader reader = storage.openRangeReader(file.getFileName().toString())) {

            FileMetaData footer = Format.readFooter(reader);
            assertThat(footer.rowGroups()).isNotEmpty();

            int columnsWithColumnIndex = 0;
            int columnsWithOffsetIndex = 0;

            for (ColumnChunk col : footer.rowGroups().get(0).columns()) {
                if (col.columnIndexOffset().isPresent()
                        && col.columnIndexLength().isPresent()) {
                    long offset = col.columnIndexOffset().getAsLong();
                    int length = col.columnIndexLength().getAsInt();
                    ColumnIndex ci = Format.readColumnIndex(reader, offset, length);
                    assertThat(ci.nullPages())
                            .as("null_pages must not be empty")
                            .isNotEmpty();
                    assertThat(ci.minValues())
                            .as("min_values must match null_pages size")
                            .hasSameSizeAs(ci.nullPages());
                    assertThat(ci.maxValues())
                            .as("max_values must match null_pages size")
                            .hasSameSizeAs(ci.nullPages());
                    assertThat(ci.boundaryOrder())
                            .as("boundary_order must be set")
                            .isNotNull();
                    columnsWithColumnIndex++;
                }
                if (col.offsetIndexOffset().isPresent()
                        && col.offsetIndexLength().isPresent()) {
                    long offset = col.offsetIndexOffset().getAsLong();
                    int length = col.offsetIndexLength().getAsInt();
                    OffsetIndex oi = Format.readOffsetIndex(reader, offset, length);
                    assertThat(oi.pageLocations())
                            .as("page_locations must not be empty")
                            .isNotEmpty();
                    for (var loc : oi.pageLocations()) {
                        assertThat(loc.compressedPageSize())
                                .as("compressed_page_size must be positive")
                                .isPositive();
                    }
                    columnsWithOffsetIndex++;
                }
            }

            // parquet-avro with 1000 rows writes page indexes; assert at least one column has each
            assertThat(columnsWithColumnIndex)
                    .as("at least one column should have a column index")
                    .isGreaterThan(0);
            assertThat(columnsWithOffsetIndex)
                    .as("at least one column should have an offset index")
                    .isGreaterThan(0);
        }
    }

    /**
     * Verifies that a PageHeader can be read from the start of the first data page of the first column chunk in a
     * Parquet file.
     *
     * <p>Uses a 256-byte window starting at {@code data_page_offset}, which is always sufficient to cover the
     * compact-encoded PageHeader (typically under 50 bytes).
     */
    @Test
    void readsFirstDataPageHeader(@TempDir Path tmp) throws Exception {
        Path file = TestFiles.flatIntSnappy(tmp);
        try (Storage storage = StorageFactory.open(file.getParent().toUri());
                RangeReader reader = storage.openRangeReader(file.getFileName().toString())) {

            FileMetaData footer = Format.readFooter(reader);
            ColumnChunk firstCol = footer.rowGroups().get(0).columns().get(0);
            long pageStart = firstCol.metaData().orElseThrow().dataPageOffset();

            // Read a small window; PageHeader is at most ~100 bytes in practice
            ByteBuffer buf = reader.readRange(pageStart, 256);
            buf.flip();

            byte[] bytes = new byte[buf.remaining()];
            buf.get(bytes);
            try (InputStream is = new ByteArrayInputStream(bytes)) {
                PageHeader header = Format.readPageHeader(is);
                assertThat(header.type())
                        .as("first page type must be a valid page type")
                        .isIn(PageType.DATA_PAGE, PageType.DATA_PAGE_V2, PageType.DICTIONARY_PAGE);
                assertThat(header.compressedPageSize())
                        .as("compressed_page_size must be positive")
                        .isPositive();
                assertThat(header.uncompressedPageSize())
                        .as("uncompressed_page_size must be positive")
                        .isPositive();
            }
        }
    }

    /**
     * Verifies that column and offset indexes can be read for a nullable-column fixture, which exercises the null_pages
     * and null_counts fields of ColumnIndex.
     */
    @Test
    void columnIndexWithNullableColumnsReadable(@TempDir Path tmp) throws Exception {
        Path file = TestFiles.nullableFlat(tmp);
        try (Storage storage = StorageFactory.open(file.getParent().toUri());
                RangeReader reader = storage.openRangeReader(file.getFileName().toString())) {

            FileMetaData footer = Format.readFooter(reader);
            assertThat(footer.rowGroups()).isNotEmpty();

            for (ColumnChunk col : footer.rowGroups().get(0).columns()) {
                if (col.columnIndexOffset().isPresent()
                        && col.columnIndexLength().isPresent()) {
                    long offset = col.columnIndexOffset().getAsLong();
                    int length = col.columnIndexLength().getAsInt();
                    ColumnIndex ci = Format.readColumnIndex(reader, offset, length);
                    assertThat(ci.nullPages()).isNotEmpty();
                    assertThat(ci.minValues()).hasSameSizeAs(ci.nullPages());
                    assertThat(ci.maxValues()).hasSameSizeAs(ci.nullPages());
                }
            }
        }
    }

    /**
     * Verifies that page headers and indexes are readable across all row groups of a multi-row-group fixture,
     * validating the multi-row-group case.
     */
    @Test
    void indexesReadableInMultiRowGroupFile(@TempDir Path tmp) throws Exception {
        Path file = TestFiles.multiRowGroup(tmp);
        try (Storage storage = StorageFactory.open(file.getParent().toUri());
                RangeReader reader = storage.openRangeReader(file.getFileName().toString())) {

            FileMetaData footer = Format.readFooter(reader);
            assertThat(footer.rowGroups()).hasSizeGreaterThan(1);

            for (var rowGroup : footer.rowGroups()) {
                for (ColumnChunk col : rowGroup.columns()) {
                    if (col.offsetIndexOffset().isPresent()
                            && col.offsetIndexLength().isPresent()) {
                        long offset = col.offsetIndexOffset().getAsLong();
                        int length = col.offsetIndexLength().getAsInt();
                        OffsetIndex oi = Format.readOffsetIndex(reader, offset, length);
                        assertThat(oi.pageLocations()).isNotEmpty();
                    }
                }
            }
        }
    }
}
