<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.tileverse.parquetry</groupId>
    <artifactId>parquetry-parent</artifactId>
    <version>${revision}</version>
  </parent>

  <artifactId>parquetry-integrations</artifactId>
  <packaging>pom</packaging>
  <name>Parquetry :: Integrations</name>
  <description>Parent and aggregator for parquetry adapters to other ecosystems</description>

  <modules>
    <module>parquetry-avro</module>
    <module>parquetry-arrow</module>
    <module>parquetry-jackson</module>
    <module>parquetry-tileverse-storage</module>
    <module>parquetry-geotools</module>
    <module>parquetry-iceberg</module>
    <module>parquetry-stac</module>
  </modules>
</project>
